### ISSUE TITLE
cdk deploy Applications fails with error: no endpoints available for service "aws-load-balancer-webhook-service"

### ISSUE THREAD

**Issue by sihamekchiouch** [aws-samples/one-observability-demo#170]
### Description

cdk deploy Applications fails with the following error:

```
Received response status [FAILED] from custom resource. Message returned: Error: b'serviceaccount/petsite-sa created 
service/service-petsite created deployment.apps/petsite-deployment created Error from server (InternalError): error 
when creating "/tmp/manifest.yaml": Internal error occurred: failed calling webhook "mtargetgroupbinding.elbv2.k8s.aws": 
Post "https://aws-load-balancer-webhook-service.kube-system.svc:443/mutate-elbv2-k8s-aws-v1beta1-targetgroupbinding?timeout=10s": 
no endpoints available for service "aws-load-balancer-webhook-service"' 
Logs: /aws/lambda/Applications-ApplicationsMyCluster-Handler886CB40B-8Jm2SKKdx3fi at invokeUserFunction (/var/task/framework.js:2:6) 
at processTicksAndRejections (internal/process/task_queues.js:95:5) 
at async onEvent (/var/task/framework.js:1:302) at async Runtime.handler (/var/task/cfn-response.js:1:1474) 
(RequestId: 33613a8c-ea0a-4d60-b3c7-4131a54df851)

```
so we couldn't really make much progress, as this setup step is needed, before getting into the more interesting content of the workshop

**Comment by awsimaya** [comment]
Can you please try redeploying the app?
