### ISSUE TITLE
Stack fails

### ISSUE THREAD

**Issue by ashishvd1** [aws-samples/one-observability-demo#201]
The first stack itself fails. 
-------------------
[ERROR]	2023-02-01T02:54:03.361Z	0d0b484a-a3ce-4481-8b37-a95a6c1b4d29	An error occurred (IncorrectState) when calling the AssociateIamInstanceProfile operation: There is an existing association for instance i-00fd9028cfc49c644
Traceback (most recent call last):
  File "/var/task/index.py", line 43, in lambda_handler
    response = ec2.associate_iam_instance_profile(IamInstanceProfile=iam_instance_profile, InstanceId=instance['InstanceId'])
  File "/var/runtime/botocore/client.py", line 391, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/var/runtime/botocore/client.py", line 719, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (IncorrectState) when calling the AssociateIamInstanceProfile operation: There is an existing association for instance i-00fd9028cfc49c644
----------------------

**Comment by gtantachuco** [comment]
I am experiencing the same issue. Is there a workaround?

**Comment by snypher** [comment]
Same error here when trying to deploy in my own AWS account (not at AWS event)

**Comment by AWS-Joe-A** [comment]
Hello @ashishvd1,
Thank you for your patience. I have recently on boarded to the team and I'm following up with issues for this project. 
I don't believe this is an issue now as we have moved away from Cloud9. 

Can you confirm that we can close out this issue?
