### ISSUE TITLE
cdk deployment failing in Services

### ISSUE THREAD

**Issue by discoverrahul-11** [aws-samples/one-observability-demo#202]
Tried deployment of observability workshop several times in Singapore and sydney regions and hitting error as attached.
Pls help to fix this issue.

upon execution of line "cdk deploy --context admin_role=$EKS_ADMIN_ARN Services --context dashboard_role_arn=$CONSOLE_ROLE_ARN --require-approval never"

ervices: creating CloudFormation changeset...
[████████████████████████████████████████████████▌·········] (159/190)
6:02:01 AM | CREATE_FAILED        | Custom::AWSCDK-EKS-KubernetesResource       | petsiteAwsAuthmanifest576F9E03
Received response status [FAILED] from custom resource. Message returned: StateNotFoundError: State functionActiveV2 not found.
at constructor.loadWaiterConfig (/var/runtime/node_modules/aws-sdk/lib/resource_waiter.js:196:32)
at new constructor (/var/runtime/node_modules/aws-sdk/lib/resource_waiter.js:64:10)
at features.constructor.waitFor (/var/runtime/node_modules/aws-sdk/lib/service.js:271:18)
at Object.defaultInvokeFunction [as invokeFunction] (/var/task/outbound.js:1:826)
at processTicksAndRejections (internal/process/task_queues.js:95:5)
at async invokeUserFunction (/var/task/framework.js:1:2149)
at async onEvent (/var/task/framework.js:1:365)
at async Runtime.handler (/var/task/cfn-response.js:1:1543) (RequestId: 2e08bf6c-281d-4211-8d79-11ee2b366eae)
----------------------------------------------------------------------------------

Another error at times on repeat trying is as below:
Applications: creating CloudFormation changeset...

   Applications failed: Error [ValidationError]: Unable to fetch parameters [/eks/pethistory/TargetGroupArn,/eks/petsite/EKSMasterRoleArn,/eks/petsite/OIDCProviderArn,/eks/petsite/OIDCProviderUrl,/eks/petsite/TargetGroupArn,/petstore/rdssecretarn] from parameter store for this account.
    at Request.extractError (/home/ec2-user/.nvm/versions/node/v16.19.0/lib/node_modules/aws-cdk/lib/index.js:31:33843)
    at Request.callListeners (/home/ec2-user/.nvm/versions/node/v16.19.0/lib/node_modules/aws-cdk/lib/index.js:31:76646)
    at Request.emit (/home/ec2-user/.nvm/versions/node/v16.19.0/lib/node_modules/aws-cdk/lib/index.js:31:76094)
    at Request.emit (/home/ec2-user/.nvm/versions/node/v16.19.0/lib/node_modules/aws-cdk/lib/index.js:31:182419)
    at Request.transition (/home/ec2-user/.nvm/versions/node/v16.19.0/lib/node_modules/aws-cdk/lib/index.js:31:175971)
    at AcceptorStateMachine.runTo (/home/ec2-user/.nvm/versions/node/v16.19.0/lib/node_modules/aws-cdk/lib/index.js:31:140843)
    at /home/ec2-user/.nvm/versions/node/v16.19.0/lib/node_modules/aws-cdk/lib/index.js:31:141173
    at Request.<anonymous> (/home/ec2-user/.nvm/versions/node/v16.19.0/lib/node_modules/aws-cdk/lib/index.js:31:176263)
    at Request.<anonymous> (/home/ec2-user/.nvm/versions/node/v16.19.0/lib/node_modules/aws-cdk/lib/index.js:31:182494)
    at Request.callListeners (/home/ec2-user/.nvm/versions/node/v16.19.0/lib/node_modules/aws-cdk/lib/index.js:31:76814) {
  code: 'ValidationError',
  time: 2023-02-22T05:15:10.216Z,
  requestId: '70ad13e5-de8c-4b6b-b89b-2e56fd96a86f',
  statusCode: 400,
  retryable: false,
  retryDelay: 307.5156220368398
}

**Comment by mohamed-haidara-cko** [comment]
+1 Same error here in `us-east-1` when running `cdk deploy Applications --require-approval never` in `PetAdoptions/cdk/pet_stack`

<details>
<summary>Details</summary>

```
 ❌ Deployment failed: Error [ValidationError]: Unable to fetch parameters [/eks/pethistory/TargetGroupArn,/eks/petsite/EKSMasterRoleArn,/eks/petsite/OIDCProviderArn,/eks/petsite/OIDCProviderUrl,/eks/petsite/TargetGroupArn,/petstore/rdssecretarn] from parameter store for this account.
    at Request.extractError (/home/ubuntu/.nvm/versions/node/v21.5.0/lib/node_modules/aws-cdk/lib/index.js:366:46692)
    at Request.callListeners (/home/ubuntu/.nvm/versions/node/v21.5.0/lib/node_modules/aws-cdk/lib/index.js:366:91404)
    at Request.emit (/home/ubuntu/.nvm/versions/node/v21.5.0/lib/node_modules/aws-cdk/lib/index.js:366:90852)
    at Request.emit (/home/ubuntu/.nvm/versions/node/v21.5.0/lib/node_modules/aws-cdk/lib/index.js:366:199248)
    at Request.transition (/home/ubuntu/.nvm/versions/node/v21.5.0/lib/node_modules/aws-cdk/lib/index.js:366:192800)
    at AcceptorStateMachine.runTo (/home/ubuntu/.nvm/versions/node/v21.5.0/lib/node_modules/aws-cdk/lib/index.js:366:157672)
    at /home/ubuntu/.nvm/versions/node/v21.5.0/lib/node_modules/aws-cdk/lib/index.js:366:158002
    at Request.<anonymous> (/home/ubuntu/.nvm/versions/node/v21.5.0/lib/node_modules/aws-cdk/lib/index.js:366:193092)
    at Request.<anonymous> (/home/ubuntu/.nvm/versions/node/v21.5.0/lib/node_modules/aws-cdk/lib/index.js:366:199323)
    at Request.callListeners (/home/ubuntu/.nvm/versions/node/v21.5.0/lib/node_modules/aws-cdk/lib/index.js:366:91572) {
  code: 'ValidationError',
  time: 2023-12-30T18:32:06.607Z,
  requestId: 'df3b9399-c06a-4d0c-a4c2-27bb54733e55',
  statusCode: 400,
  retryable: false,
  retryDelay: 619.5858354474016
}

Unable to fetch parameters [/eks/pethistory/TargetGroupArn,/eks/petsite/EKSMasterRoleArn,/eks/petsite/OIDCProviderArn,/eks/petsite/OIDCProviderUrl,/eks/petsite/TargetGroupArn,/petstore/rdssecretarn] from parameter store for this account.
c
```
</details>

**Comment by AWS-Joe-A** [comment]
Hello @discoverrahul-11 @mohamed-haidara-cko ,
Thank you for your patience. I have recently on boarded to the team and I'm following up with issues for this project. I was able to deploy the latest build successfully. 

Can you confirm if this is still an issue?

**Comment by AWS-Joe-A** [comment]
Closing the issue since I have not heard back. Please reopen if you are still experiencing the same issue.
