### ISSUE TITLE
Issue noted when creating EKS-Kubernetes resources

### ISSUE THREAD

**Issue by andrewboyd79** [aws-samples/one-observability-demo#214]
9:25:28 AM | CREATE_FAILED        | Custom::AWSCDK-EKS-KubernetesResource       | ssmAgentdeployment/Resource/Default
Received response status [FAILED] from custom resource. Message returned: StateNotFoundError: State functionActiveV2 not found.
at constructor.loadWaiterConfig (/var/runtime/node_modules/aws-sdk/lib/resource_waiter.js:196:32)
at new constructor (/var/runtime/node_modules/aws-sdk/lib/resource_waiter.js:64:10)
at features.constructor.waitFor (/var/runtime/node_modules/aws-sdk/lib/service.js:271:18)
at defaultInvokeFunction (/var/task/outbound.js:1:826)
at processTicksAndRejections (internal/process/task_queues.js:95:5)
at async invokeUserFunction (/var/task/framework.js:1:2192)
at async onEvent (/var/task/framework.js:1:369)
at async Runtime.handler (/var/task/cfn-response.js:1:1573) (RequestId: d7c4447d-e60f-40d5-8540-1ac4a6c3e53b)

**Comment by AWS-Joe-A** [comment]
Hello @andrewboyd79, 
Thank you for your patience. I have recently on boarded to the team and I'm following up with issues for this project. 
I was able to deploy the workshop successfully using the current code. 

Can you confirm if this is still an issue for you?

**Comment by AWS-Joe-A** [comment]
Closing the issue since I have not heard back. Please reopen if you are still experiencing the same issue.
