### ISSUE TITLE
Services stack failed 

### ISSUE THREAD

**Issue by sebastianalfaro** [aws-samples/one-observability-demo#223]
Hello, 

I am using a fresh AWS account with full IAM admin permissions. After getting to resource 188/198, the stack fails to create the following resources. Following the One Observability Workshop here https://catalog.workshops.aws/observability/en-US/installation/not-using-ee/deploy-app

5:22:21 AM | CREATE_FAILED        | Custom::AWSCDK-EKS-KubernetesResource       | xraydeployment/Resource/Default
Received response status [FAILED] from custom resource. Message returned: AccessDeniedException: Resource is not in the state functionActive
at Object.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/json.js:52:27)
at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/rest_json.js:61:8)
at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:686:14)
at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)
at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)
at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10
at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)
at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:688:12) (RequestId: c1d0cf25-d230-418e-a8a5-f873027682e7)

5:22:21 AM | CREATE_FAILED        | Custom::AWSCDK-EKS-KubernetesResource       | petsite/AwsAuth/ma...t/Resource/Default
Received response status [FAILED] from custom resource. Message returned: AccessDeniedException: Resource is not in the state functionActive
at Object.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/json.js:52:27)
at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/rest_json.js:61:8)
at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:686:14)
at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)
at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)
at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10
at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)
at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:688:12) (RequestId: b90f105e-3086-4eba-9c15-935e1347ec26)

5:22:21 AM | CREATE_FAILED        | Custom::AWSCDK-EKS-KubernetesResource       | ssmAgentdeployment/Resource/Default
Received response status [FAILED] from custom resource. Message returned: AccessDeniedException: Resource is not in the state functionActive
at Object.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/json.js:52:27)
at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/rest_json.js:61:8)
at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:686:14)
at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)
^[c

Any assistant would be appreciated!

**Comment by weklund** [comment]
I'm getting the same error.  Brand new account with admin permissions

**Comment by AWS-Joe-A** [comment]
Hello @weklund @sebastianalfaro , 
Thank you for your patience. I have recently on boarded to the team and I'm following up with issues for this project. 
I was able to successfully deploy the current code. 

Can you confirm if you are still seeing this issue?

**Comment by AWS-Joe-A** [comment]
Closing the issue since I have not heard back. Please reopen if you are still experiencing the same issue.
