### ISSUE TITLE
Setup Cloud9 environment fails as cloudformation stack creation fails

### ISSUE THREAD

**Issue by gkovan** [aws-samples/one-observability-demo#228]
The cloudformation template fails when setting up the cloud9 environment.

I followed the steps in the workshop: https://catalog.us-east-1.prod.workshops.aws/workshops/31676d37-bbe9-4992-9cd1-ceae13c5116c/en-US/installation/not-using-ee/setup-cloud9

and got the following error:

<img width="1112" alt="Screenshot 2023-06-05 at 9 06 24 AM" src="https://github.com/aws-samples/one-observability-demo/assets/17445316/2395b4cf-e17a-4850-91b2-b0d2a5501a92">

The following errors showed up in the cloudwatch logs:

```
[ERROR]	2023-06-05T12:29:25.650Z	cd03876b-0d8a-4166-aaeb-e0c01bebd771	An error occurred (IncorrectState) when calling the AssociateIamInstanceProfile operation: There is an existing association for instance i-07e943ccbf113d5f8
Traceback (most recent call last):
  File "/var/task/index.py", line 43, in lambda_handler
    response = ec2.associate_iam_instance_profile(IamInstanceProfile=iam_instance_profile, InstanceId=instance['InstanceId'])
  File "/var/runtime/botocore/client.py", line 530, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/var/runtime/botocore/client.py", line 960, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (IncorrectState) when calling the AssociateIamInstanceProfile operation: There is an existing association for instance i-07e943ccbf113d5f8
```

and 

```
{
    "Status": "FAILED",
    "Reason": "See the details in CloudWatch Log Stream: 2023/06/05/[$LATEST]d8291b9393434b33820461d3ed667311",
    "PhysicalResourceId": "CustomResourcePhysicalID",
    "StackId": "arn:aws:cloudformation:us-east-1:577619097681:stack/C9-Observability-Workshop/3c9715a0-039c-11ee-8fec-0ea25af41d31",
    "RequestId": "f6606300-2ae2-4639-b374-c35c9462872e",
    "LogicalResourceId": "C9BootstrapInstanceLambda",
    "NoEcho": false,
    "Data": {
        "Error": "There was a problem associating IAM profile to the Cloud9 Instance"
    }
}
```

**Comment by snypher** [comment]
Same error here when trying to deploy in my own AWS account (not at an AWS event)

**Comment by snypher** [comment]
This same issue was reported on Feb 1
https://github.com/aws-samples/one-observability-demo/issues/201

**Comment by awsimaya** [comment]
@rafaelpereyra , can you take a look at this please?

**Comment by AWS-Joe-A** [comment]
This is not an issue as we are no longer using Cloud9. 
I will close out this issue.

**Comment by AWS-Joe-A** [comment]
Closing the issue since I have not heard back. Please reopen if you are still experiencing the same issue.
