### ISSUE TITLE
getting error while deploying cdk stack

### ISSUE THREAD

**Issue by vikasj003** [aws-samples/one-observability-demo#235]
10:39:24 AM | CREATE_FAILED        | Custom::AWSCDK-EKS-KubernetesResource       | ssmAgentdeployment/Resource/Default
Received response status [FAILED] from custom resource. Message returned: AccessDeniedException: Resource is not in the state functionActive
at Object.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/json.js:61:27)
at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/rest_json.js:61:8)
at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:686:14)
at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)
at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)
at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10
at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)
at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:688:12) (RequestId: 13bbd8c8-b697-4661-be52-97a9b7589069)
10:39:24 AM | CREATE_FAILED        | Custom::AWSCDK-EKS-KubernetesResource       | loadBalancerCRD/Resource/Default
Received response status [FAILED] from custom resource. Message returned: AccessDeniedException: Resource is not in the state functionActive
at Object.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/json.js:61:27)
at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/rest_json.js:61:8)
at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:686:14)
at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)
at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)
at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10
at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)
at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:688:12) (RequestId: 2414184d-fba4-4d93-a591-4635521c97da)
10:39:27 AM | ROLLBACK_IN_PROGRESS | AWS::CloudFormation::Stack                  | Services
The following resource(s) failed to create: [LBServiceAccount67A900BC, loadBalancerServiceAccount1D19AD3A, ssmAgentdeployment3666D473, xraydeployment7059A3EB, petsiteAwsAuth
manifest576F9E03, k8sdashboardrbac66807D7E, loadBalancerCRDEF35F65C, cloudwatcheployment7FE6A515]. Rollback requested by user.
10:39:27 AM | ROLLBACK_IN_PROGRESS | AWS::CloudFormation::Stack                  | Services
The following resource(s) failed to create: [LBServiceAccount67A900BC, loadBalancerServiceAccount1D19AD3A, ssmAgentdeployment3666D473, xraydeployment7059A3EB, petsiteAwsAuth
manifest576F9E03, k8sdashboardrbac66807D7E, loadBalancerCRDEF35F65C, cloudwatcheployment7FE6A515]. Rollback requested by user.

**Comment by vikasj003** [comment]
how to resolve this error

**Comment by vikasj003** [comment]
Any update on this

**Comment by vikasj003** [comment]
Any update on this

**Comment by AWS-Joe-A** [comment]
Hello @vikasj003,
Thank you for your patience. I have recently on-boarded to the team and I'm following up with issues for this project. 
I was able to deploy the current code successfully. 

Could you confirm if you still receive the same error?

**Comment by AWS-Joe-A** [comment]
Closing the issue since I have not heard back. Please reopen if you are still experiencing the same issue.
