### ISSUE TITLE
AccessDeniedException:  Resource is not in the state functionActive

### ISSUE THREAD

**Issue by dangnhuhieu** [aws-samples/one-observability-demo#238]
On my own AWS(with AdminFullAcess login user) fail at command:
cdk deploy Applications --require-approval never

with error:
Received response status [FAILED] from custom resource. 
Message returned: AccessDeniedException: 
Resource is not in the state functionActive at 
Object.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/json.js:61:27) 
at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/rest_json.js:61:8) 
at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20) 
at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:78:10) 
at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:686:14) 
at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10) 
at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12) 
at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10 
at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9) 
at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:688:12) 
(RequestId: f3c6e4ed-324f-47f8-925d-52d7b9955ba7)

<img width="1409" alt="Ảnh chụp Màn hình 2023-07-15 lúc 21 30 38" src="https://github.com/aws-samples/one-observability-demo/assets/38760858/afc2956a-3b8c-4fd2-9343-f26ef5c5244f">

Please help me!

**Comment by nrxlor** [comment]
encountered the same question

**Comment by AWS-Joe-A** [comment]
Hello @dangnhuhieu @nrxlor, 
Thank you for your patience. I have recently on boarded to the team and I'm following up with issues for this project. 
I was able to deploy the latest code successfully in my account. 

Can you confirm if this is still an issue for you?

**Comment by AWS-Joe-A** [comment]
Closing the issue since I have not heard back. Please reopen if you are still experiencing the same issue.
