### ISSUE TITLE
Doesn't work with Kubernetes 1.26 or higher

### ISSUE THREAD

**Issue by Anorlondo448** [aws-samples/one-observability-demo#273]
An error occurs at "Deploy the stack".

https://catalog.us-east-1.prod.workshops.aws/workshops/31676d37-bbe9-4992-9cd1-ceae13c5116c/en-US/installation/deploy-app#deploy-the-stack
```
Received response status [FAILED] from custom resource. Message returned: Error: b'configmap/otel-config created\nerror: error retrieving RESTMappings to prune: invalid resource batch/v1beta1, Kind=CronJob, Namespaced=true: no matches for kind "CronJob" in version "batch/v1beta1"\n' Logs: /aws/lambda/Applications-ApplicationsMyCluster-Handler886CB40B-NYL3nXTBbQdU at invokeUserFunction (/var/task/framework.js:2:6) at process.processTicksAndRejections (node:internal/process/task_queues:95:5) at async onEvent (/var/task/framework.js:1:369) at async Runtime.handler (/var/task/cfn-response.js:1:1676) (RequestId: 06f4983c-a2d3-428d-8a11-4cc3e9f509c4)
```

If I set the Kubernetes version to 1.25, the error will no longer occur.
https://github.com/aws-samples/one-observability-demo/blob/43a60adf4fff0c839c611afdbd3782c8ac5e3a25/PetAdoptions/cdk/pet_stack/lib/services.ts#L344

related issue
https://github.com/aws-quickstart/cdk-eks-blueprints/issues/713

**Comment by AWS-Joe-A** [comment]
Hello @Anorlondo448, 
Thank you for your patience. I have recently joined the team and I'm following up on issues. 
We have updated the content since this was posted. Can you confirm if this is still an issue?
