### ISSUE TITLE
loadtest trafficgenerator is broken

### ISSUE THREAD

**Issue by wnbts** [aws-samples/one-observability-demo#35]
The instructions on https://observability.workshop.aws/en/scaleup/_load_test.html are not working as expected to generate traffic.

The error message that might be useful.

```
trafficgenerator_1_54383a96569d | ENVIRONMENT NAME IS: Production
trafficgenerator_1_54383a96569d | info: trafficgenerator.Worker[0]
trafficgenerator_1_54383a96569d |       Worker running at: 10/24/2020 00:45:40 +00:00
trafficgenerator_1_54383a96569d | System.InvalidOperationException: An invalid request URI was provided. The request URI must either be an absolute URI or BaseAddress must be set.
trafficgenerator_1_54383a96569d |    at System.Net.Http.HttpClient.PrepareRequestMessage(HttpRequestMessage request)
trafficgenerator_1_54383a96569d |    at System.Net.Http.HttpClient.SendAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
trafficgenerator_1_54383a96569d |    at System.Net.Http.HttpClient.GetStringAsync(String requestUri)
trafficgenerator_1_54383a96569d |    at trafficgenerator.Worker.LoadPetData() in /src/Worker.cs:line 59
trafficgenerator_1_54383a96569d |    at trafficgenerator.Worker.ThrowSomeTrafficIn() in /src/Worker.cs:line 66
trafficgenerator_1_54383a96569d |    at trafficgenerator.Worker.ExecuteAsync(CancellationToken stoppingToken) in /src/Worker.cs:line 43
trafficgenerator_1_54383a96569d | info: Microsoft.Hosting.Lifetime[0]
trafficgenerator_1_54383a96569d |       Application started. Press Ctrl+C to shut down.
```

**Comment by awsimaya** [comment]
Hello, sorry about this issue. We have completely revamped that part now. Please check the changes here - https://observability.workshop.aws/en/scaleup.html
